import { chromium } from '@playwright/test'
const [,, outDir, w = '1440', scheme = 'light'] = process.argv
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const p = await b.newPage({ viewport: { width: +w, height: 900 }, colorScheme: scheme })
const errors = []
p.on('pageerror', (e) => errors.push(String(e)))
p.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()) })
await p.goto('http://localhost:3000/#demo', { waitUntil: 'networkidle' })
const demo = p.locator('#demo')
await demo.scrollIntoViewIfNeeded(); await p.waitForTimeout(900)
// keyboard: focus first service button and press Enter
await p.getByRole('button', { name: /Colour refresh/ }).focus()
await p.keyboard.press('Enter')
await p.waitForTimeout(700)
console.log('focused after service:', await p.evaluate(() => document.activeElement?.textContent))
await demo.screenshot({ path: `${outDir}/demo-2-${w}-${scheme}.png` })
const times = p.locator('#demo ul button.tabular')
console.log('times:', await times.count())
await times.nth(2).click()
await p.waitForTimeout(700)
console.log('focused after time:', await p.evaluate(() => document.activeElement?.textContent))
await demo.screenshot({ path: `${outDir}/demo-3-${w}-${scheme}.png` })
await p.getByRole('button', { name: 'Confirm booking' }).click()
await p.waitForTimeout(900)
console.log('focused after confirm:', await p.evaluate(() => document.activeElement?.textContent))
console.log('live:', await p.locator('#demo [aria-live]').textContent())
await demo.screenshot({ path: `${outDir}/demo-4-${w}-${scheme}.png` })
if (errors.length) console.log('ERRORS', errors)
await b.close()
