// Generated by scripts/i18n-registry.mjs. Do not edit by hand.
import type { Locale } from './config'

import type booking from './messages/en/booking.json'
import type common from './messages/en/common.json'
import type email from './messages/en/email.json'
import type errors from './messages/en/errors.json'

export type Catalogues = {
  'booking': typeof booking
  'common': typeof common
  'email': typeof email
  'errors': typeof errors
}
export type Namespace = keyof Catalogues

export const NAMESPACES = ["booking","common","email","errors"] as const satisfies readonly Namespace[]

type Loader = () => Promise<{ default: unknown }>

/** Lazy loaders: a catalogue is only read when a page needs it. */
export const loaders: Partial<Record<Locale, Partial<Record<Namespace, Loader>>>> = {
  ar: {
    'common': () => import('./messages/ar/common.json'),
  },
  de: {
    'common': () => import('./messages/de/common.json'),
  },
  el: {
    'common': () => import('./messages/el/common.json'),
  },
  en: {
    'booking': () => import('./messages/en/booking.json'),
    'common': () => import('./messages/en/common.json'),
    'email': () => import('./messages/en/email.json'),
    'errors': () => import('./messages/en/errors.json'),
  },
  es: {
    'common': () => import('./messages/es/common.json'),
  },
  fr: {
    'common': () => import('./messages/fr/common.json'),
  },
  hi: {
    'common': () => import('./messages/hi/common.json'),
  },
  it: {
    'common': () => import('./messages/it/common.json'),
  },
  ja: {
    'common': () => import('./messages/ja/common.json'),
  },
  nl: {
    'common': () => import('./messages/nl/common.json'),
  },
  pl: {
    'common': () => import('./messages/pl/common.json'),
  },
  pt: {
    'common': () => import('./messages/pt/common.json'),
  },
  ru: {
    'common': () => import('./messages/ru/common.json'),
  },
  tr: {
    'common': () => import('./messages/tr/common.json'),
  },
  zh: {
    'common': () => import('./messages/zh/common.json'),
  },
}
